##### Tile Configuration

########################
# HOW TO USE THIS FILE:
#
# This file provides tile-specific configuration for a tile on a given foundation
# You will need a private git repository
#
# - Make a copy of this template. Rename using slug (e.g. p-rabbitmq.yml, pivotal-mysql.yml, etc)
# - Set the slug and version in section 1 as desired
# - Update the slugs and versions in section 2 accordingly
# - Use the 'design.sh' script to process this file and produce
#   a list of parameters for section 3
# - Add/remove values from 'ops_files' in section 2 below as
#   needed, and rerun 'design.sh' to re-generate section 3 params
#   until desired configuration is achieved
#      Note:
#      - paths in section 2 are relative to output of tile-config-generator tool
#      - tile-config-generator tool is available for reference at:
#        https://github.com/DaxterM/tile-configuration
#      - Use "vars" as destination of output for tcg tool/repo clone
#      - vars_files and ops_files can each be a space-delimited list
#      - For empty ops_files, use "ops_files:  env/common/config/templates/empty-file.yml"
#      - Note that 'config_file' does not need to specify a parent dir above the slug
# - When satisfied with ops_files, copy the parameters provided by 'design.sh'
#   into section 3 below
# - Provide values for the params in section 3
# Follow the directions in the README or in `config-template-common.yml` to create
#     a separate common config file for the foundation
# Push this file to your private repo using the following naming convention:
#    - <private-repo-root>/((foundation))/((pivnet-product-slug)).yml
# Run the script `fly-set-pipeline.sh`
########################

##### SECTION 1 - Basics
pivnet_product_slug: p-some-slug
product_version: "1.2.3"
pivnet_file_glob: "p-some-slug*.pivotal"
stemcell_iaas: "google"

##### SECTION 2 - Config files
# vars_files and ops_files can be space-delimited list
# Paths are relative to output of tile-config-generator tool
#   See https://github.com/DaxterM/tile-configuration for reference
#   Use "vars" as destination of output for tcg tool/repo clone
#   Note that 'config_file' does not need to specify a parent dir above the slug

config_file: p-some-slug/1.2.3/product.yml

vars_files: vars/p-some-slug/1.2.3/product-default-vars.yml vars/p-some-slug/1.2.3/resource-vars.yml vars/p-some-slug/1.2.3/errand-vars.yml

ops_files: vars/p-some-slug/1.2.3/features/some-file.yml vars/p-some-slug/1.2.3/features/some-other-file.yml

##### SECTION 3 - Config parameters
some_parameter: some-value
