resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tags: latest-final

resources:
- name: pcf-automation
  type: pivnet
  source:
    api_token: {{pivnet_api_token}}
    product_slug: platform-automation

- name: tcg-config
  type: git
  source:
    uri: https://github.com/DaxterM/tile-configuration.git

- name: configuration
  type: git
  source:
    uri: git@github.com:ciberkleid/platform-automation.git
    private_key: {{git_private_key}}

- name: credentials
  type: git
  source:
    uri: git@github.com:ciberkleid/platform-automation-private.git
    private_key: {{git_private_key}}

jobs:
- name: ((foundation))-((pivnet_product_slug))
  serial: true
  plan:
  - aggregate:
    - get: configuration
      trigger: false
      params:
        unpack: true
    - get: pcf-automation-image
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: pcf-automation-tasks
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: credentials
      params:
        unpack: true
    - get: tcg-config
      params:
        unpack: true

  - task: creds-interpolate
    image: pcf-automation-image
    file: configuration/fixes/tasks/creds-interpolate.yml
    input_mapping:
      config: configuration
      vars: credentials
    params:
      VARS_FILES: vars/((foundation))/common.yml
      CONFIG_FILE: common/config/templates/env.yml
    output_mapping:
      interpolated-files: configuration

  - task: download-product
    image: pcf-automation-image
    file: configuration/fixes/tasks/download-product.yml
    input_mapping:
      config: configuration
      secrets: credentials
    params:
      CONFIG_FILE: common/config/templates/pivnet.yml
      VARS_FILES: secrets/((foundation))/common.yml secrets/((foundation))/((pivnet_product_slug)).yml

  - task: upload-product
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/upload-product.yml
    input_mapping:
      product: downloaded-product
      env: configuration
    params:
      ENV_FILE: common/config/templates/env.yml

  - task: stage-product
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/stage-product.yml
    input_mapping:
      product: downloaded-product
      env: configuration
    params:
      ENV_FILE: common/config/templates/env.yml

  - task: upload-stemcell
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/upload-stemcell.yml
    input_mapping:
      env: configuration
      stemcell: downloaded-stemcell
    params:
      ENV_FILE: common/config/templates/env.yml

  - task: assign-stemcell
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/assign-stemcell.yml
    input_mapping:
      env: configuration
      config: assign-stemcell-config
    params:
      ENV_FILE: common/config/templates/env.yml

  - task: configure-product
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: tcg-config
      env: configuration
      vars: tcg-config
      secrets: credentials
    params:
      CONFIG_FILE: ((config_file))
      OPS_FILES: ((ops_files))
      VARS_FILES: ((vars_files)) secrets/((foundation))/((pivnet_product_slug)).yml
      ENV_FILE: common/config/templates/env.yml


# - name: apply-changes
#   serial: true
#   plan:
#   - aggregate:
#     - get: configuration
#       trigger: true
#       passed: [ ((foundation))-((pivnet_product_slug)) ]
#       params:
#         unpack: true
#     - get: pcf-automation-image
#       resource: pcf-automation
#       params:
#         unpack: true
#         globs: ["*image*"]
#     - get: pcf-automation-tasks
#       resource: pcf-automation
#       params:
#         unpack: true
#         globs: ["*tasks*"]
#
#   - task: apply-product-changes
#     image: pcf-automation-image
#     file: pcf-automation-tasks/tasks/apply-changes.yml
#     input_mapping:
#       env: configuration
#     params:
#       ENV_FILE: common/config/templates/env.yml
