##### Common Configuration
foundation: toolsmiths-pas
opsman_host: pcf.abc.cf-app.com
opsman_userid: pivotalcf
opsman_password: my-opsman-password
opsman_decryption_passphrase:
pivnet_api_token: my-token
git_private_repo: git@github.com:my-username/my-private-repo.git
git_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEAvwkL97vBllOSE39Wa5ppczT1cr5Blmkhadfoa1Va2/IBVyvk
  NJ9PqoTI+BahF2EgzweyiDSvKsstlTsG7QgiM9So8Voi2PlDOrXL6uOfCuAS/G8X
  ...
  AXvHfOx5zhtOsx3j9CKanRXfHfXSANUC+/McpszjWuz3pbWkPhbzRnHJSLFP
  -----END RSA PRIVATE KEY-----

##### Common Tile Configuration
stemcell_iaas: "google"
network_name: abc-pas-subnet
service_network_name: abc-services-subnet
singleton_availability_zone: us-central1-f
az2_name: us-central1-c
az3_name: us-central1-b
# The following common tile configuration values should not be changed
config_file: product.yml
vars_files: vars/product-default-vars.yml vars/resource-vars.yml vars/errand-vars.yml
