##### Tile Configuration

##### SECTION 1 - Basics
pivnet_product_slug: p-cloudcache
product_version: "1.6.1"
product_build: "1.6.1-build.5" # used by design-config.sh
pivnet_file_glob: "p-cloudcache*.pivotal"

##### SECTION 2 - Config files
##### SECTION 2 - Config files
# - If no ops_files are needed, specify "ops_files: "
ops_files: network/3-az-configuration.yml features/errand_plan-plan1.yml

##### SECTION 3 - Config parameters
confirm_tls_setup: X

dev_plan_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f', 'us-central1-c', 'us-central1-b' ]

plan1_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f', 'us-central1-c', 'us-central1-b' ]
plan2_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f', 'us-central1-c', 'us-central1-b' ]
plan3_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f', 'us-central1-c', 'us-central1-b' ]
plan4_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f', 'us-central1-c', 'us-central1-b' ]
plan5_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f', 'us-central1-c', 'us-central1-b' ]

small_footprint_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f', 'us-central1-c', 'us-central1-b' ]
