##### Tile Configuration

##### SECTION 1 - Basics
pivnet_product_slug: p-cloudcache
product_version: "1.6.1"
product_build: "1.6.1-build.5" # used by config-designer.sh
pivnet_file_glob: "p-cloudcache*.pivotal"
stemcell_iaas: "google"

##### SECTION 2 - Config files
config_file: p-cloudcache/1.6.1-build.5/product.yml

vars_files: vars/p-cloudcache/1.6.1-build.5/product-default-vars.yml vars/p-cloudcache/1.6.1-build.5/resource-vars.yml vars/p-cloudcache/1.6.1-build.5/errand-vars.yml

ops_files: vars/p-cloudcache/1.6.1-build.5/features/errand_plan-plan1.yml

##### SECTION 3 - Config parameters
network_name: abc-pas-subnet
service_network_name: abc-services-subnet
singleton_availability_zone: us-central1-f

confirm_tls_setup: X

dev_plan_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f' ]

plan1_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f' ]
plan2_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f' ]
plan3_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f' ]
plan4_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f' ]
plan5_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f' ]

small_footprint_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f' ]
