##### Tile Configuration

##### SECTION 1 - Basics
pivnet_product_slug: p-rabbitmq
product_version: "1.16.3"
product_build: "1.16.3" # used by design-config.sh
pivnet_file_glob: "p-rabbitmq*.pivotal"

##### SECTION 2 - Config files
# - If no ops_files are needed, specify "ops_files: "
ops_files: network/3-az-configuration.yml features/syslog_selector-disabled.yml features/multitenant_support-enabled.yml

##### SECTION 3 - Config parameters
on_demand_broker_plan_1_rabbitmq_az_placement: [ 'us-central1-f', 'us-central1-c', 'us-central1-b' ]

multitenant_support/enabled/broker_operator_set_policy_enabled:
multitenant_support/enabled/disk_alarm_threshold:
multitenant_support/enabled/server_admin_credentials_identity: username
multitenant_support/enabled/server_admin_credentials_password: password
multitenant_support/enabled/server_cluster_partition_handling: pause_minority
multitenant_support/enabled/server_ports: 15672, 5672, 5671, 1883, 8883, 61613, 61614, 15674
multitenant_support/enabled/server_ssl_verification_depth: 5
