##### Tile Configuration

#####
# To change the tile configuration, add or remove ops_files and use
# design-config.sh to product the list of params for section 3
#   ref: https://github.com/ciberkleid/platform-automation/blob/master/design-config.sh
#
# For list of ops_files to choose from, use "tile-config-generator" or refer to the following repo
#   ref: https://github.com/DaxterM/tile-configuration
#####

##### SECTION 1 - Basics
pivnet_product_slug: p-rabbitmq
product_version: "1.15.4"
product_build: "1.15.4" # used by design-config.sh
pivnet_file_glob: "p-rabbitmq*.pivotal"
stemcell_iaas: "google"

##### SECTION 2 - Config files
# - Paths for config_file, vars_files, and ops_files are relative to
#   the output of the "tile-config-generator" tool
#   (see https://github.com/DaxterM/tile-configuration for reference)
# - vars_files and ops_files can be space-delimited lists
# - Prefix paths to vars_files with "vars/"
# - If no ops_files are needed, specify "ops_files: "

config_file: p-rabbitmq/1.15.4/product.yml

vars_files: vars/p-rabbitmq/1.15.4/product-default-vars.yml vars/p-rabbitmq/1.15.4/resource-vars.yml vars/p-rabbitmq/1.15.4/errand-vars.yml

ops_files: p-rabbitmq/1.15.4/features/syslog_selector-disabled.yml p-rabbitmq/1.15.4/features/multitenant_support-enabled.yml

##### SECTION 3 - Config parameters
network_name: abc-pas-subnet
service_network_name: abc-services-subnet
singleton_availability_zone: us-central1-f

on_demand_broker_plan_1_rabbitmq_az_placement: [ 'us-central1-f' ]

multitenant_support/enabled/broker_operator_set_policy_enabled:
multitenant_support/enabled/disk_alarm_threshold:
multitenant_support/enabled/server_admin_credentials_identity: my-username
multitenant_support/enabled/server_admin_credentials_password: my-password
multitenant_support/enabled/server_cluster_partition_handling: pause_minority
multitenant_support/enabled/server_ports: 15672, 5672, 5671, 1883, 8883, 61613, 61614, 15674
multitenant_support/enabled/server_ssl_verification_depth: 5
