##### Tile Configuration

#####
# To change the tile configuration, add or remove ops_files and use
# design-config.sh to product the list of params for section 3
#   ref: https://github.com/ciberkleid/platform-automation/blob/master/design-config.sh
#
# For list of ops_files to choose from, use "tile-config-generator" or refer to the following repo
#   ref: https://github.com/DaxterM/tile-configuration
#####

##### SECTION 1 - Basics
pivnet_product_slug: p-spring-cloud-services
product_version: "2.0.6"
product_build: "2.0.6" # used by design-config.sh
pivnet_file_glob: "p-spring-cloud-services*.pivotal"
stemcell_iaas: "google"

##### SECTION 2 - Config files
# - Paths for config_file, vars_files, and ops_files are relative to
#   the output of the "tile-config-generator" tool
#   (see https://github.com/DaxterM/tile-configuration for reference)
# - vars_files and ops_files can be space-delimited lists
# - Prefix paths to vars_files with "vars/"
# - If no ops_files are needed, specify "ops_files: "

config_file: p-spring-cloud-services/2.0.6/product.yml

vars_files: vars/p-spring-cloud-services/2.0.6/product-default-vars.yml vars/p-spring-cloud-services/2.0.6/resource-vars.yml vars/p-spring-cloud-services/2.0.6/errand-vars.yml

ops_files:

##### SECTION 3 - Config parameters
network_name: abc-pas-subnet
singleton_availability_zone: us-central1-f
