##### Tile Configuration

##### SECTION 1 - Basics
pivnet_product_slug: p-spring-cloud-services
product_version: "2.0.6"
product_build: "2.0.6" # used by design-config.sh
pivnet_file_glob: "p-spring-cloud-services*.pivotal"
stemcell_iaas: "google"

##### SECTION 2 - Config files
# - If no ops_files are needed, specify "ops_files: "
ops_files:

##### SECTION 3 - Config parameters
