##### Tile Configuration

##### SECTION 1 - Basics
pivnet_product_slug: pivotal-mysql
product_version: "2.5.4"
product_build: "2.5.4-build.51" # used by design-config.sh
pivnet_file_glob: "pivotal-mysql*.pivotal"

##### SECTION 2 - Config files
##### SECTION 2 - Config files
# - If no ops_files are needed, specify "ops_files: "
ops_files: network/3-az-configuration.yml features/backups_selector-s3.yml

##### SECTION 3 - Config parameters
deprecated_bindings_string: X
global_recipient_email: donotreply@nowhere.io

plan1_selector/single_node/az_multi_select: [ 'us-central1-f', 'us-central1-c', 'us-central1-b' ]
plan2_selector/single_node/az_multi_select: [ 'us-central1-f', 'us-central1-c', 'us-central1-b' ]
plan3_selector/single_node/az_multi_select: [ 'us-central1-f', 'us-central1-c', 'us-central1-b' ]

backups_selector/s3/access_key_id: your-access-key-id
backups_selector/s3/secret_access_key: your-secret-access-key
backups_selector/s3/bucket_name: your-bucket-name
backups_selector/s3/path: mysql
backups_selector/s3/cron_schedule: 0 */8 * * *
backups_selector/s3/enable_email_alerts:
