##### Common Configuration

########################
# HOW TO USE THIS FILE:
#
# This file provides common configuration for a given foundation
# You will need a private git repository
#
# Copy this template and update the values so that they are valid
# Push this file to your private repo using the following naming convention:
#    - <private-repo-root>/((foundation))/common.yml
# Follow the directions in the README or in `config-template.yml` to create
#     a separate tile-specific config file
# Run the script `fly-set-pipeline.yml`
########################

foundation: toolsmiths-pas
opsman_host: pcf.abc.cf-app.com
opsman_userid: pivotalcf
opsman_password: my-opsman-password
opsman_decryption_passphrase:
pivnet_api_token: my-token
git_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEAvwkL97vBllOSE39Wa5ppczT1cr5Blmkhadfoa1Va2/IBVyvk
  NJ9PqoTI+BahF2EgzweyiDSvKsstlTsG7QgiM9So8Voi2PlDOrXL6uOfCuAS/G8X
  ...
  AXvHfOx5zhtOsx3j9CKanRXfHfXSANUC+/McpszjWuz3pbWkPhbzRnHJSLFP
  -----END RSA PRIVATE KEY-----
