##### Tile Configuration

#####
# To change the tile configuration, add or remove ops_files and use
# config-designer.sh to product the list of params for section 3
#   ref: https://github.com/ciberkleid/platform-automation/blob/master/config-designer.sh
#
# For list of ops_files to choose from, use "tile-config-generator" or refer to the following repo
#   ref: https://github.com/DaxterM/tile-configuration
#####

##### SECTION 1 - Basics
pivnet_product_slug: p-product-slug
product_version: "1.2.3"
product_build: "1.2.3-build.4" # used by config-designer.sh
pivnet_file_glob: "p-product-slug*.pivotal"
stemcell_iaas: "google"

##### SECTION 2 - Config files
# - Paths for config_file, vars_files, and ops_files are relative to
#   the output of the "tile-config-generator" tool
#   (see https://github.com/DaxterM/tile-configuration for reference)
# - vars_files and ops_files can be space-delimited lists
# - Prefix paths to vars_files with "vars/"
# - If no ops_files are needed, specify "ops_files: "

config_file: p-product-slug/1.2.3-build.4/product.yml

vars_files: vars/p-product-slug/1.2.3-build.4/product-default-vars.yml vars/p-product-slug/1.2.3-build.4/resource-vars.yml vars/p-product-slug/1.2.3-build.4/errand-vars.yml

ops_files: p-product-slug/1.2.3-build.4/features/options_file_1.yml p-product-slug/1.2.3-build.4/features/options_file_2.yml

##### SECTION 3 - Config parameters
network_name: abc-pas-subnet
service_network_name: abc-services-subnet
singleton_availability_zone: us-central1-f

plan1_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f' ]
plan2_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f' ]
plan3_enable_service_plan/enable/service_instance_azs: [ 'us-central1-f' ]
